import { readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = new URL('../', import.meta.url);

function buildMap(directory, exportName) {
  const files = readdirSync(new URL(`../assets/catalog/${directory}/`, import.meta.url))
    .filter((file) => /\.(jpg|jpeg|png)$/i.test(file))
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
  const entries = files.map((file) => {
    const key = file.replace(/\.[^.]+$/, '');
    return `  ${JSON.stringify(key)}: require('../../assets/catalog/${directory}/${file}'),`;
  });
  return `export const ${exportName}: Record<string, number> = {\n${entries.join('\n')}\n};\n`;
}

const output = [
  '// Generated by scripts/generateImageAssets.mjs.\n',
  buildMap('planets', 'PLANET_ASSETS'),
  buildMap('messier', 'MESSIER_ASSETS'),
].join('\n');

writeFileSync(join(root.pathname, 'src/data/imageAssets.ts'), output);
